name: Django CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Print Python version
        run: python --version

      - name: Print pip version
        run: pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv --python 3.9
          pipenv install --dev

      - name: Run migrations
        run: |
          cd django-todo-react/backend
          pipenv run python manage.py migrate

      - name: Run tests
        run: |
          cd django-todo-react/backend
          pipenv run python manage.py test todo/tests.py
